
name: OpenWrt Build CI

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      tag:
        required: false
        type: string


jobs:
  build:
    name: Build x86_64 OpenWrt Firmware
    runs-on: ubuntu-24.04
    if: github.event.repository.owner.id == github.event.sender.id
    outputs:
      is_release: ${{ steps.ctx.outputs.is_release }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: openwrt-musl-lite
            config: base_musl_config
            target: musl
          - name: openwrt-glibc-lite
            config: base_glibc_config
            target: glibc
          - name: openwrt-musl-full
            config: full_musl_config
            target: musl
          - name: openwrt-glibc-full
            config: full_glibc_config
            target: glibc
            
    steps:
      - name: Set workspace
        run: |
          sudo mkdir -p -m 777 /mnt/openwrt
          echo "WORK_PATH=/mnt/openwrt" >> $GITHUB_ENV
          sudo -E timedatectl set-timezone Asia/Shanghai

      - name: Resolve build context
        id: ctx
        run: |
          EVENT="${{ github.event_name }}"

          if [[ "$EVENT" == "workflow_call" || "$EVENT" == "workflow_dispatch" ]]; then
            REF="${{ inputs.ref }}"
            TAG="${{ inputs.tag }}"
          elif [[ "$EVENT" == "push" && "${GITHUB_REF}" == refs/tags/* ]]; then
            REF="${GITHUB_SHA}"
            TAG="${GITHUB_REF#refs/tags/}"
          else
            REF="${GITHUB_SHA}"
            TAG=""
          fi

          echo "ref=$REF" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT

          if [[ "$TAG" == v* ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Show build type
        run: |
          echo "REF: ${{ steps.ctx.outputs.ref }}"
          echo "TAG: ${{ steps.ctx.outputs.tag }}"
          echo "Release: ${{ steps.ctx.outputs.is_release }}"

      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ steps.ctx.outputs.ref }}
          path: openwrt
          
      - name: Configure compilation environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt update -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
            bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
            g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
            libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
            libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
            ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
            python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
            upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd yasm
          df -h

      - name: Change Build Path
        run: |
          sudo rsync -a "$GITHUB_WORKSPACE/openwrt/" ${{ env.WORK_PATH }}/        

      - name: Update feeds
        working-directory: ${{ env.WORK_PATH }}
        run: |
          ./tool.sh feed

      - name: Generate configuration file
        working-directory: ${{ env.WORK_PATH }}
        run: |
          rm -f ./.config*
          cp ./configs/${{ matrix.config }} ./.config
          make defconfig
          make download -j8
          df -h

      - name: Compile firmware
        run: |
          cd ${{ env.WORK_PATH }}
          make -j$(($(nproc) + 1))  || make -j1 V=s      

      - name: Clean Build Files
        working-directory: ${{ env.WORK_PATH }}
        run: |
          rm -rf ./staging_dir
          rm -rf ./build_dir

      - name: Prepare artifact
        working-directory: ${{ env.WORK_PATH }}
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f -name "immortalwrt-*") ./artifact/firmware/
          cp -rf $(find ./bin/targets/ -type f -name "sha256sums") ./artifact/firmware/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Clean Bin Files
        working-directory: ${{ env.WORK_PATH }}
        run: |
          rm -rf ./bin

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.name }}-buildinfo
          path: ${{ env.WORK_PATH }}/artifact/buildinfo/

      - name: Deliver firmware
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.name }}
          path: ${{ env.WORK_PATH }}/artifact/firmware/