name: OpenWrt Auto Build CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  workflow_dispatch:

concurrency:
  group: openwrt-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.sha }}

  upload_release:
    needs: build
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    uses: ./.github/workflows/upload_release.yml
    with:
      tag: ${{ github.ref_name }}
    secrets:
      release_token: ${{ secrets.RELEASE_TOKEN }}

  push_release_msg:
    needs: [build, upload_release]
    if: github.ref_type == 'tag'
    permissions:
      contents: read
    uses: ./.github/workflows/msg.yml
    secrets:
      corpid: ${{ secrets.CORPID }}
      corpsecret: ${{ secrets.CORPSECRET }}
      agentid: ${{ secrets.AGENTID }}
    with:
      msg: "Released on ${{ github.ref_name }}"

  push_snapshot_msg:
    needs: build
    if: github.ref_type != 'tag'
    permissions:
      contents: read
    uses: ./.github/workflows/msg.yml
    secrets:
      corpid: ${{ secrets.CORPID }}
      corpsecret: ${{ secrets.CORPSECRET }}
      agentid: ${{ secrets.AGENTID }}
    with:
      msg: "Snapshot on ${{ github.ref_name }}"
