name: Auto Release CI

on:
  workflow_dispatch:
  schedule:
    # 每周二触发（后面脚本判断是否第二周）
    - cron: "0 5 15 * *"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.rel.outputs.sha }}
      tag: ${{ steps.rel.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run release script
        run: |
          ./release-lock.sh

      - name: Commit release
        run: |
          VERSION=$(cat .release_version)

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add feeds.conf.default include/version.mk

          git commit -m "release ${VERSION}" || echo "Nothing to commit"

          git tag "${VERSION}"

          git push origin HEAD
          git push origin "${VERSION}"

      - name: Get release info
        id: rel
        run: |
          VERSION=$(cat .release_version)
          SHA=$(git rev-parse HEAD)

          echo "tag=$VERSION" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT
  build:
    needs: release
    uses: Coolkids/immortalwrt/.github/workflows/openwrt_build.yml@master
    with:
      ref: ${{ needs.release.outputs.sha }}
      tag: ${{ needs.release.outputs.tag }}

  revert:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
        
      - name: Revert changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git revert HEAD --no-edit
          git commit --amend -m "[skip ci] revert release changes"
          git push origin HEAD