
name: OpenWrt 24.10 Test CI

on:
  push:
    branches: 
      - openwrt-24.10

jobs:

  push_msg:
    name: push weixing msg
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set workspace
        run: |
          mkdir -p firmware
      - name: Restore cache musl
        uses: actions/cache/restore@v4
        with:
          path: musl_firmware
          key: musl_firmware
      - name: Restore cache gcc
        uses: actions/cache/restore@v4
        with:
          path: glibc_firmware
          key: glibc_firmware
      - name: Check SHA256
        run: |
          cp musl_firmware/* firmware/
          cp glibc_firmware/* firmware/
          cd firmware
          for file in *; do
            sha256sum "$file" >> ../sha256sums
          done

      - name: Upload release asset
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: firmware/*
          overwrite: true
          release_name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          file_glob: true
          body: |
            release ${{ github.ref_name }}
  
      - name: Delete loder releases
        uses: dev-drprasad/delete-older-releases@v0.3.3
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Push Msg
        run: |
          sh .github/push.sh ${{ secrets.CORPID }} ${{ secrets.CORPSECRET }} ${{ secrets.AGENTID }} "x86_64" "Released on ${{ github.ref_name }}"





