
name: OpenWrt-releases-CI

on:
  push:
    tags:
      - 'v*'
  # schedule:
  #   - cron: 0 20 * * *
  #release:
  #  types: [published]

jobs:

  build_openwrt:

    name: Build x86_64 OpenWrt firmware

    runs-on: ubuntu-22.04

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: mount sdb1
        run: |
          sudo umount /mnt
          mkdir -p /home/runner/work/immortalwrt
          sudo mount /dev/sdb1 /home/runner/work/immortalwrt
          df -h

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      
      - name: Set variables
        run: |
          sudo -E timedatectl set-timezone Asia/Shanghai

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc /etc/mysql /etc/php
          sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install libfuse-dev $(curl -fsSL git.io/depends-ubuntu-2204)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          df -h

      - name: Update feeds
        run: |
          ./tool.sh feed

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          cp .github/x86.config ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Clean Build Files
        run: |
          rm -rf ./staging_dir
          rm -rf ./build_dir

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f -name "immortalwrt-*") ./artifact/firmware/
          cp -rf $(find ./bin/targets/ -type f -name "sha256sums") ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
          
      - name: Clean Bin Files
        run: |
          rm -rf ./bin

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware
          path: ./artifact/firmware/

      - name: Upload release asset
        #if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          file: ./artifact/firmware/*
          overwrite: true
          release_name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          file_glob: true

      - name: Delete loder releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 5
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Push Msg
        run: |
          sh .github/push.sh ${{ secrets.CORPID }} ${{ secrets.CORPSECRET }} ${{ secrets.AGENTID }} "x86_64" "Released on ${{ github.ref_name }}"









