name: OpenWrt-IMQ-release-merge-CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 15 * *'

jobs:
  merge_main:
    name: merge dev into master
    runs-on: ubuntu-22.04

    steps:        
      - name: Set Env
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          echo "VERSION=$(date +'%y.%m')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PUSH_TOKEN}}
        
      - name: merge
        uses: mtanzi/action-automerge@v1
        with:
          github_token: ${{secrets.PUSH_TOKEN}}
          source: 'dev'
          target: 'master'
          
      - name: delete tag
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: v${{ env.VERSION }}
          github_token: ${{ secrets.PUSH_TOKEN }}
          delete_release: true
          
      - name: Tag release
        uses: mathieudutour/github-tag-action@v6.2
        id: tag_version
        with:
          github_token: ${{ secrets.PUSH_TOKEN }}
          release_branches: master
          custom_tag: ${{ env.VERSION }}

      - name: Push Msg
        run: |
          sh .github/push.sh ${{ secrets.CORPID }} ${{ secrets.CORPSECRET }} ${{ secrets.AGENTID }} "x86_64" "Merge dev into master ${{ steps.tag_version.outputs.new_tag }}"
